clc, clear, close all

% ========================================================
%  A MESHLESS Element-Free Galerkin (EFG) method based on 
%  Moving Least Squares (MLS) approximation
%  (Convergence Study)
%  Authors: Pr. Khennane Amar & Dr. Rahmouni Faouzi
% -----------
%  * 2D steady-state heat conduction problem in a square plate with a 
%    circular hole using a meshless Element-Free Galerkin (EFG) method 
%    based on Moving Least Squares (MLS) approximation. 
%  * A Delaunay triangulation is introduced only for numerical 
%    integration of the weak form using Gauss quadrature and does 
%    not define the approximation space. 
%  * Penalty method for boundary conditions.
% ========================================================

% 1. GEOMETRY & MATERIAL
L  = 50;          
R  = 4;           
kx = 1003; 
ky = 171;        
D_mat = [kx 0; 
         0 ky];

% 2. BOUNDARY CONDITIONS
T_hole  = 773;   
T_outer = 273;   

% 3. MESHLESS PARAMETERS
dmax_mult = 3.5;      % High overlap for smooth field
penalty_K = 1e11;     % penalty for BCs

% 4. CONVERGENCE LOOP
study_configs = [ 
    24,  8;   % Run 1: Coarse
    36, 12;   % Run 2: Medium
    48, 16;   % Run 3: Fine
    60, 20;   % Run 4: Very Fine
];

num_runs  = size(study_configs, 1);
res_T     = zeros(num_runs, 4);
res_nodes = zeros(num_runs, 1); 
res_err   = zeros(num_runs, 1); 

% Load target physical points generated by the FEM code
pts      = load('Exact_Nodes.mat'); 
pts_eval = pts.final_pts;

fprintf('Running EFG Study...\n');

for i = 1:num_runs
    
    n_circ = study_configs(i, 1);
    n_rad  = study_configs(i, 2);
    
    %% A. NODE GENERATION
    nodes  = [];
    r_vals = linspace(0, 1, n_rad).^1.2; 
    radii  = R + (L*0.8 - R) * r_vals;
    
    for r_idx = 1:length(radii)
        r = radii(r_idx);
        nc = round(n_circ * (r/R)); 
        nc = max(nc, n_circ);      
        nc = min(nc, n_circ*2.5);  
        
        th = linspace(0, 2*pi, nc+1); th(end)=[];
        x  = L/2 + r*cos(th);
        y  = L/2 + r*sin(th);
        nodes = [nodes; x' y'];
    end
    
    % Outer Box
    n_edge = n_circ;
    lx     = linspace(0, L, n_edge);
    nodes  = [nodes; lx', zeros(n_edge,1)];
    nodes  = [nodes; lx', ones(n_edge,1)*L];
    nodes  = [nodes; zeros(n_edge,1), lx'];
    nodes  = [nodes; ones(n_edge,1)*L, lx'];
    
    nodes = unique(nodes, 'rows');
    mask  = nodes(:,1)>=-0.01 & nodes(:,1)<=L+0.01 & nodes(:,2)>=-0.01 & nodes(:,2)<=L+0.01;
    nodes = nodes(mask, :);
    num_nodes = size(nodes, 1);
    
    %% B. SUPPORT RADIUS
    k_neighbors = 14; 
    dmax = zeros(num_nodes, 1);
    for k = 1:num_nodes
        d2 = (nodes(:,1)-nodes(k,1)).^2 + (nodes(:,2)-nodes(k,2)).^2;
        d2 = sort(d2);
        dmax(k) = sqrt(d2(min(k_neighbors, length(d2)))) * dmax_mult;
    end
    
    %% C. INTEGRATION MESH
    n_int_rad  = n_rad * 2; 
    n_int_circ = n_circ * 2;
    r_int  = linspace(R, L*0.9, n_int_rad);
    th_int = linspace(0, 2*pi, n_int_circ+1); th_int(end)=[];
    
    pts_layer = [];
    for r = r_int
        x = L/2 + r*cos(th_int);
        y = L/2 + r*sin(th_int);
        pts_layer = [pts_layer; x' y'];
    end
    mesh_pts = [pts_layer; 0 0; L 0; L L; 0 L]; 
    mesh_pts = unique(mesh_pts, 'rows');
    tri = delaunay(mesh_pts(:,1), mesh_pts(:,2));
    
    % Filter Triangles
    x1 = mesh_pts(tri(:,1),1); 
    y1 = mesh_pts(tri(:,1),2);
    x2 = mesh_pts(tri(:,2),1); 
    y2 = mesh_pts(tri(:,2),2);
    x3 = mesh_pts(tri(:,3),1); 
    y3 = mesh_pts(tri(:,3),2);
    xm = (x1 + x2 + x3)/3; 
    ym = (y1 + y2 + y3)/3;
    
    dist_c    = sqrt((xm-L/2).^2 + (ym-L/2).^2);
    valid_tri = dist_c >= R-1e-3 & xm>=0 & xm<=L & ym>=0 & ym<=L;
    tri = tri(valid_tri, :);
    
    num_elem     = size(tri, 1); 
    res_nodes(i) = num_nodes;
    
    %% D. ASSEMBLY
    K = sparse(num_nodes, num_nodes);
    F = zeros(num_nodes, 1);
    
    gp_r = [1/6, 2/3, 1/6];
    gp_s = [1/6, 1/6, 2/3];
    gp_w = [1/6, 1/6, 1/6];
    
    for e = 1:num_elem
        ids = tri(e,:);
        xe  = mesh_pts(ids, 1);
        ye  = mesh_pts(ids, 2);
        Area = 0.5 * abs((xe(2)-xe(1))*(ye(3)-ye(1)) - (xe(3)-xe(1))*(ye(2)-ye(1)));
        
        for gp = 1:3
            r  = gp_r(gp); s = gp_s(gp);
            xg = xe(1)*(1-r-s) + xe(2)*r + xe(3)*s;
            yg = ye(1)*(1-r-s) + ye(2)*r + ye(3)*s;
            
            if sqrt((xg-L/2)^2 + (yg-L/2)^2) < R-1e-4, continue; end
            
            wt = Area * gp_w(gp);
            [phi, B, neighbors] = MLSShapeFunc(xg, yg, nodes, dmax);
            if isempty(neighbors), continue; end
            
            k_loc = B' * D_mat * B * wt;
            K(neighbors, neighbors) = K(neighbors, neighbors) + k_loc;
        end
    end
    
    %% E. BOUNDARY CONDITIONS
    outer_idx = find(nodes(:,1)<1e-2 | nodes(:,1)>L-1e-2 | nodes(:,2)<1e-2 | nodes(:,2)>L-1e-2);
    for k = 1:length(outer_idx)
        id = outer_idx(k);
        [phi, ~, neighs] = MLSShapeFunc(nodes(id,1), nodes(id,2), nodes, dmax);
        pp = penalty_K * (phi' * phi);
        ff = penalty_K * T_outer * phi';
        K(neighs, neighs) = K(neighs, neighs) + pp;
        F(neighs) = F(neighs) + ff;
    end
    
    hole_dist = sqrt((nodes(:,1)-L/2).^2 + (nodes(:,2)-L/2).^2);
    hole_idx = find(abs(hole_dist - R) < 0.2);
    for k = 1:length(hole_idx)
        id = hole_idx(k);
        [phi, ~, neighs] = MLSShapeFunc(nodes(id,1), nodes(id,2), nodes, dmax);
        pp = penalty_K * (phi' * phi);
        ff = penalty_K * T_hole * phi';
        K(neighs, neighs) = K(neighs, neighs) + pp;
        F(neighs) = F(neighs) + ff;
    end
    
    %% F. SOLVE
    T = K \ F;
    
    %% G. EXACT POINTS & ERROR
    for pid = 1:4
        [phi, ~, neighs] = MLSShapeFunc(pts_eval(pid,1), pts_eval(pid,2), nodes, dmax);
        if ~isempty(neighs)
             val_neighs = T(neighs); 
             val_neighs = val_neighs(:); 
             phi = phi(:); 
             res_T(i, pid) = sum(phi .* val_neighs); 
        else
             res_T(i, pid) = NaN;
        end
    end
    res_err(i) = abs((res_T(i,1) - 773) / 773) * 100;
    fprintf('Run %d: Nodes=%d, Err=%.2e%%\n', i, res_nodes(i), res_err(i));

    %% H. PLOTTING
    if i == 1
        PlotMeshLess(nodes, hole_idx, L, R, num_nodes, dmax, T)
    end
end

%% ============================================================
%  OUTPUT TABLES
% ============================================================
fprintf('\n===========================================================================\n');
fprintf(' EFG CONVERGENCE RESULTS\n');
fprintf('===========================================================================\n');
fprintf('%-10s %-10s %-10s %-10s %-10s %-15s\n', 'Nodes', 'A', 'B', 'C', 'D', 'Val. Error (%)');
fprintf('---------------------------------------------------------------------------\n');
for i = 1:num_runs
    fprintf('%-10d %-10.2f %-10.2f %-10.2f %-10.2f %-15.2e\n', ...
      res_nodes(i), res_T(i,1), res_T(i,2), res_T(i,3), res_T(i,4), res_err(i));
end
fprintf('---------------------------------------------------------------------------\n');
