%% ========================================================================
%  SCRIPT:   HBSpline_Tab23_Validation.m
%  TYPE:     Isogeometric Analysis (IGA) Solver
%  METHOD:   Hierarchical B-Splines (HB-Splines)
%  PROBLEM:  2D Orthotropic Heat Conduction (Steady State)
%
%  AUTHORS:  Dr. Rahmouni Faouzi | Email: rahmounifaouzi01@gmail.com
%            Pr. Khennane Amar   | Email: a.khennane@adfa.edu.au
%
%  DESCRIPTION:
%    Solves the Laplace/Poisson equation for heat transfer on a rectangular
%    plate using a 2-level Hierarchical B-Spline mesh.
%    - Level 0: Coarse base mesh.
%    - Level 1: Local refinement in the center (40%-60% of domain).
%    - Implements Dirichlet boundary conditions (fixed temperatures).
%    - Uses exact subdivision matrices for Coarse-to-Fine projection.
% =========================================================================

clc, clear, close all, warning off
addpath(genpath('../Functions'));

%%  1. PROBLEM DEFINITION & INPUT PARAMETERS
%  =========================================

% -- Material Properties (Orthotropic) --
kx = 1003;              % Thermal conductivity in x-direction [W/mK]
ky = 171;               % Thermal conductivity in y-direction [W/mK]
D = [kx 0;              % Conductivity Matrix
     0 ky];

% -- Boundary Conditions (Dirichlet) --
T0 = 273;               % Temperature at boundaries left, right and bottom
Tg = 773;               % Temperature at top boundary  

% -- Geometry Dimensions --
a = 100;                 % Plate Length (x-direction) 
b = 100;                 % Plate Height (y-direction)

% -- HB-Spline degree --
p = 2;                 % HB-Spline degree in u-direction
q = 2;                 % HB-Spline degree in v-direction

% -- Discretization Parameters --
xMesh = [8 10 12 14 16 18 20 22 24 26 28 30 40];
yMesh = xMesh;
TA = zeros(numel(xMesh),1);
TB = TA; TC = TA; TD = TA; dt = TA;
total_elements = TA;

fprintf('--- Analysis starts ---\n');
fprintf('order is p = %d and q = %d\n', p, q);

for ref = 1:numel(xMesh)
    t_start = tic;
    ne_x = xMesh(ref);               % Number of coarse elements in x
    ne_y = yMesh(ref);               % Number of coarse elements in y
    
    % -- Derived Grid Spacing --
    dx = a / ne_x;          % Coarse element width
    dy = b / ne_y;          % Coarse element height
    
    %%  2. KNOT VECTOR CONSTRUCTION
    %  ============================
    % -- Level 0 (Coarse) Knots --
    % Linear spacing between 0 and 1
    u_internal_0 = linspace(0, 1, ne_x+1);
    v_internal_0 = linspace(0, 1, ne_y+1);
    
    % Pad knots with multiplicity (p+1) at boundaries (Open Knot Vector)
    U0 = [zeros(1,p), u_internal_0, ones(1,p)];
    V0 = [zeros(1,q), v_internal_0, ones(1,q)];
    
    % -- Level 1 (Fine) Knots --
    % Generated by bisecting every interval of the coarse knot vector
    u_mid = (u_internal_0(1:end-1) + u_internal_0(2:end)) / 2;
    v_mid = (v_internal_0(1:end-1) + v_internal_0(2:end)) / 2;
    
    % Merge and sort to create the refined knot vector
    u_internal_1 = sort([u_internal_0, u_mid]);
    v_internal_1 = sort([v_internal_0, v_mid]);
    
    uKnot = [zeros(1,p), u_internal_1, ones(1,p)];
    vKnot = [zeros(1,q), v_internal_1, ones(1,q)];
    
    % Validate Knot Vector Lengths
    % -- Control Point Counts --
    ncp0_x = length(U0) - p - 1;   
    ncp0_y = length(V0) - q - 1;
    ncp1_x = length(uKnot) - p - 1;   
    ncp1_y = length(vKnot) - q - 1;
    
    %%  3. HIERARCHICAL REFINEMENT STRATEGY
    %  ====================================
    % -- Define Refinement Region --
    % Target Area: x within [40%, 60%], y within [40%, 100%]
    ex_start = round((0.4 * a) / dx) + 1;
    ex_end   = round((0.6 * a) / dx);
    ey_start = round((0.4 * b) / dy) + 1;
    ey_end   = ne_y;
    
    % -- Create Refinement Mask --
    % RefinedFlags(i,j) = 1 implies element (i,j) is subdivided
    RefinedFlags = zeros(ne_x, ne_y);
    RefinedFlags(ex_start:ex_end, ey_start:ey_end) = 1;
    
    % Count elements for reporting
    num_refined_blocks = sum(RefinedFlags(:));
    num_coarse_active  = numel(RefinedFlags) - num_refined_blocks;
    total_elements(ref) = num_coarse_active + (num_refined_blocks * 4);
    
    %%  4. BUILD PROJECTION MATRIX (M)
    %  ===============================
    %  The projection matrix T (or M) maps the reduced basis (hierarchical)
    %  to the full fine basis. It handles the linear dependence between levels.
    ndof_fine = ncp1_x * ncp1_y;
    
    % -- Compute Subdivision Matrices (S) --
    % S maps Coarse Control Points -> Fine Control Points
    Sx = HB_Subdivision(U0, p);
    Sy = HB_Subdivision(V0, q);
    
    % -- Identify Independent Fine DOFs --
    % A fine DOF is independent if its support is strictly inside the refinement zone.
    u_min_ref = U0(p + ex_start);
    u_max_ref = U0(p + ex_end + 1);
    v_min_ref = V0(q + ey_start);
    v_max_ref = V0(q + ey_end + 1);
    
    IsFineInterior = zeros(ncp1_x, ncp1_y);
    tol = 1e-8;
    
    for j = 1:ncp1_y
        for i = 1:ncp1_x
            % parametric center of the basis function
            u_g = sum(uKnot(i+1:i+p)) / p;
            v_g = sum(vKnot(j+1:j+q)) / q;
            
            % Check if basis function is fully contained in refinement zone
            if (u_g > u_min_ref + tol && u_g < u_max_ref - tol) && ...
                    (v_g > v_min_ref + tol && v_g < v_max_ref - tol)
                IsFineInterior(i,j) = 1;
            end
        end
    end
    
    % -- Generate Mapping for Reduced System --
    num_coarse     = ncp0_x * ncp0_y;
    num_fine_added = sum(IsFineInterior(:));
    num_reduced    = num_coarse + num_fine_added;
    
    FineToReducedMap = zeros(ncp1_x, ncp1_y);
    count = num_coarse;
    
    for j = 1:ncp1_y
        for i = 1:ncp1_x
            if IsFineInterior(i,j)
                count = count + 1;
                FineToReducedMap(i,j) = count;
            end
        end
    end
    
    % -- Assemble Sparse Projection Matrix T --
    I_idx = []; J_idx = []; Val = [];
    
    for j = 1:ncp1_y
        for i = 1:ncp1_x
            row_idx = (j-1) * ncp1_x + i; % Global Index (Fine Mesh)
            
            if IsFineInterior(i,j)
                % CASE A: Independent Fine Node -> Maps directly to itself in Reduced system
                col_idx = FineToReducedMap(i,j);
                I_idx = [I_idx; row_idx];
                J_idx = [J_idx; col_idx];
                Val   = [Val; 1.0];
            else
                % CASE B: Dependent (Slave) Node -> Projected onto Coarse Parents
                % Used for transitional regions to ensure continuity
                kx_indices = find(Sx(i,:));
                ky_indices = find(Sy(j,:));
                for k = kx_indices
                    for l = ky_indices
                        weight  = Sx(i,k) * Sy(j,l);
                        col_idx = (l-1) * ncp0_x + k; % Global Index (Coarse Mesh)
                        I_idx   = [I_idx; row_idx];
                        J_idx   = [J_idx; col_idx];
                        Val     = [Val; weight];
                    end
                end
            end
        end
    end
    
    T_mat = sparse(I_idx, J_idx, Val, ndof_fine, num_reduced);
    
    %%  5. FINITE ELEMENT ASSEMBLY
    %  ===========================
    K_fine = sparse(ndof_fine, ndof_fine);
    [gp, gw] = HB_lgwt(p+1, -1, 1); % Gauss-Legendre Quadrature
    
    % Loop over ALL fine elements 
    for j = 1:(2*ne_y)
        for i = 1:(2*ne_x)
            
            % 1. Determine parametric bounds for current element
            span_u = p + i;
            span_v = q + j;
            u_min = uKnot(span_u); u_max = uKnot(span_u+1);
            v_min = vKnot(span_v); v_max = vKnot(span_v+1);
            
            % 2. Identify contributing basis functions (support)
            idx_u = (span_u-p):span_u;
            idx_v = (span_v-q):span_v;
            
            % 3. Build Scatter Vector (Global DOF indices for this element)
            sctr = [];
            for vk = idx_v
                for uk = idx_u
                    sctr = [sctr, (vk-1)*ncp1_x + uk];
                end
            end
            
            % 4. Numerical Integration (Gauss Loop)
            Ke = zeros(length(sctr));
            for l = 1:numel(gp)
                for k = 1:numel(gp)
                    % Parametric Mapping: [-1,1] -> [u_min, u_max]
                    u  = ((u_max-u_min)*gp(k) + (u_max+u_min))/2;
                    v  = ((v_max-v_min)*gp(l) + (v_max+v_min))/2;
                    
                    % Jacobian determinant for integration
                    % J = (du/dxi) * (dv/deta) * det(Mapping to Physical)
                    % Here, physical mapping is linear (a*u, b*v), so J_phys = a*b
                    Jw = ((u_max-u_min)/2) * ((v_max-v_min)/2) * gw(k) * gw(l);
                    
                    % Evaluate Basis Functions and Derivatives
                    [Nu, dNu] = HB_BasisFuns(span_u, u, p, uKnot);
                    [Nv, dNv] = HB_BasisFuns(span_v, v, q, vKnot);
                    
                    % Build B-Matrix (Strain-Displacement equivalent)
                    % dN/dx = (dN/du) * (du/dx) = dN/du * (1/a)
                    B = zeros(2, length(sctr));
                    c = 0;
                    for jj = 1:length(Nv)
                        for ii = 1:length(Nu)
                            c = c + 1;
                            B(1,c) = dNu(ii)*Nv(jj) / a; % dN/dx
                            B(2,c) = Nu(ii)*dNv(jj) / b; % dN/dy
                        end
                    end
                    
                    % Accumulate Stiffness: B' * D * B * Volume
                    Ke = Ke + (B' * D * B) * (Jw * a * b);
                end
            end
            
            % Add element stiffness to global fine stiffness matrix
            K_fine(sctr, sctr) = K_fine(sctr, sctr) + Ke;
        end
    end
    
    % Project Full Fine Stiffness Matrix to Reduced Hierarchical Space
    K = T_mat' * K_fine * T_mat;
    
    %%  6. BOUNDARY CONDITIONS & SOLVER
    %  ================================
    fixed = [];
    val   = [];
    
    % -- Apply BCs to Coarse DOFs --
    for j = 1:ncp0_y
        for i = 1:ncp0_x
            dof = (j-1)*ncp0_x + i;
            
            % Get parametric coordinates of the control point
            u = sum(U0(i+1:i+p))/p;
            v = sum(V0(j+1:j+q))/q;
            
            % Check Geometric Boundaries
            if u < tol || u > 1-tol || v < tol
                fixed = [fixed; dof];
                val   = [val; T0]; % Fixed T0 at x=0, x=L, y=0
            elseif v > 1-tol
                fixed = [fixed; dof];
                val   = [val; Tg]; % Fixed Tg at y=H
            end
        end
    end
    
    % -- Apply BCs to Fine Interior DOFs --
    for j = 1:ncp1_y
        for i = 1:ncp1_x
            if IsFineInterior(i,j)
                dof = FineToReducedMap(i,j);
                u = sum(uKnot(i+1:i+p))/p;
                v = sum(vKnot(j+1:j+q))/q;
                
                if u < tol || u > 1-tol || v < tol
                    fixed = [fixed; dof];
                    val   = [val; T0];
                elseif v > 1-tol
                    fixed = [fixed; dof];
                    val   = [val; Tg];
                end
            end
        end
    end
    
    % -- Partition System Matrices --
    free    = setdiff(1:num_reduced, fixed);
    Sol_red = zeros(num_reduced, 1);
    F       = zeros(num_reduced, 1); % No internal heat generation
    
    % Apply Dirichlet Values
    Sol_red(fixed) = val;
    
    % -- Solve Linear System (Ku = F) --
    % F_free_corrected = F_free - K_constrained * U_constrained
    Sol_red(free) = K(free, free) \ (F(free) - K(free, fixed) * Sol_red(fixed));
    
    % Project solution back to Fine Grid for visualization
    T = T_mat * Sol_red;
    
    %%  7. POST-PROCESSING & VISUALIZATION
    %  ===================================
    % -- Define Points 
    pts = [0.5*a, 0.500*b;
           0.5*a, 0.625*b;
           0.5*a, 0.750*b;
           0.5*a, 0.875*b];
    ev_points = {'A','B','C','D'};
    
    TA(ref) = HB_eval_tempurature(pts(1, :), uKnot, vKnot, p, q, a, b, ncp1_x, T);
    TB(ref) = HB_eval_tempurature(pts(2, :), uKnot, vKnot, p, q, a, b, ncp1_x, T);
    TC(ref) = HB_eval_tempurature(pts(3, :), uKnot, vKnot, p, q, a, b, ncp1_x, T);
    TD(ref) = HB_eval_tempurature(pts(4, :), uKnot, vKnot, p, q, a, b, ncp1_x, T);
    
    % 2. DISPLAY PROGRESS
    dt(ref) = toc(t_start);
    fprintf('Mesh %d * %d done in %.4f sec\n', ne_x, ne_y, dt(ref));
end

fprintf('--- Analysis done in %.4f sec ---\n', sum(dt));

% DISPLAY RESULTS TABLE
%% ========================================================
fprintf('\nHB-Spline Based-IGA Orthotropic Results (K)\n');
fprintf('-------------------------------------------------------------\n');
fprintf('%-10s %8s %8s %8s %8s\n', 'Number of Elements', 'A', 'B', 'C', 'D');
for i = 1:numel(xMesh)
    fprintf('      %d          %8.2f %8.2f %8.2f %8.2f\n', ...
        total_elements(i), TA(i), TB(i), TC(i), TD(i));
end
fprintf('-------------------------------------------------------------\n');
fprintf('%-10s         %8.2f %8.2f %8.2f %8.2f\n\n', 'Analytical', 287.17, 309.66, 367.32, 507.70);

% -- Plot the tempurature field --
HB_Temp_field(pts, a, b, uKnot, vKnot, ncp1_x, ne_x, ne_y, dx, dy, p, q, T, RefinedFlags)